title: Michael Aliotti
description: ''

author:
  name: Michael Aliotti
  email: michael@michaelaliotti.com

url: 'https://michaelaliotti.com'
permalink: /:title/

# Build settings

plugins:
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

# Theme settings

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'

titles_from_headings:
  enabled: true
  strip_title: false
  collections: true
